# fly.toml file generated for throbbing-morning-3705 on 2023-04-03T09:42:38-04:00

app = "throbbing-morning-3705"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "iad"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
